avoid unnecessary Sprintf
PaulSonOfLars/gotgbot pull request #76
Opened 2023-01-08 15:37 UTC by vassilit

`Sprintf` should be less efficient than `Join`, as we are effectively joining two strings by a separator.
The «proper» way could have been to use the `net/url` package, but `Join` is simpler.

2023-01-09 14:47 UTC, PaulSonOfLars requested changes
You're right, let's just use `url.JoinPath` here; that seems much cleaner, and removes the need for the `strings.Suffix`!

I guess it could cause issues if the `data.urlPath` contained extra slashes; but I think we can cross that bridge when we get to it, seems safe enough for now. What do you think?

2023-01-09 18:10 UTC, vassilit commented
> You're right, let's just use url.JoinPath here; that seems much cleaner, and removes the need for the strings.Suffix!

Yes, but we should modify go.mod also, because `url.JoinPath` appeared in Go 1.19.

> I guess it could cause issues if the data.urlPath contained extra slashes

if `data.urlPath` contain extra slashes right now, this is already a problem, as we don't know how the telegram server will handle ".././../" in URLs. We could use `url.PathEscape` on the urlPath part.

2023-01-09 22:29 UTC, PaulSonOfLars commented
> Yes, but we should modify go.mod also, because `url.JoinPath` appeared in Go 1.19.

Ahh, thats why. Makes sense, guess we should wait on that for a bit then. Shame.

> if `data.urlPath` contain extra slashes right now, this is already a problem, as we don't know how the telegram server will handle ".././../" in URLs. We could use `url.PathEscape` on the urlPath part.

True. Eh, I'm OK with calling that user error. We probably shouldnt mess with that input too much, since itll be used by the user in other places.

2023-01-10 15:19 UTC, PaulSonOfLars approved these changes
LGTM, but good to note we can update to url.JoinPath when the module gets upgraded to 1.19

2023-01-10 16:37 UTC, merged